central:
  root: .
  reports:
    datastores:
      - artifact://inuatsu/python-monorepo-sample/common-coverage-report
      - artifact://inuatsu/python-monorepo-sample/pytest-common-coverage-report
  badges:
    datastores:
      - local://badges
  push:
    if: is_pull_request
    message: Update by octocov [skip ci]
