central:
  root: .
  reports:
    datastores:
      - artifact://inuatsu/python-monorepo-sample/common-coverage-report-libs_common
      - artifact://inuatsu/python-monorepo-sample/pytest-common-coverage-report-libs_pytest-common
  badges:
    datastores:
      - local://badges
  push:
    if: is_pull_request
    message: Update by octocov [skip ci]
