name: Unit tests

on:
  push:

jobs:
  check-diff:
    outputs:
      common-diff: ${{ steps.common_diff.outputs.diff }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set target branches
        id: target_branch
        run: |
          set -xv
          from="${{ toJSON(github.event.before) }}"
          to="${{ toJSON(github.event.after) }}"
          {
            echo "from=${from}"
            echo "to=${to}"
          } >> "$GITHUB_OUTPUT"
      - name: Get diff of libs/common directory
        id: common_diff
        run: |
          set -xv
          diff=$(git diff --diff-filter="ACDMRTUXB" --name-only "${{ steps.target_branch.outputs.from }}...${{ steps.target_branch.outputs.to }}") -- "libs/common/**" | xargs)
          echo "diff=$diff" >> "$GITHUB_ENV"
  common-test:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
      contents: write
      pull-requests: write
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get full Python version
        id: full-python-version
        run: echo "version=$(python -c 'import sys; print("-".join(str(v) for v in sys.version_info))')" >> $GITHUB_OUTPUT
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "libs/common/uv.lock"
      - name: Install dependencies
        run: uv sync --group dev
      - name: Run tests
        run: uv run poe test --cov-report xml
        working-directory: libs/common
      - if: ${{ !cancelled() }}
        uses: k1LoW/octocov-action@v1
        with:
          config: libs/common/.octocov.yml
