name: Unit tests

on:
  pull_request:
  push:
    branches:
      - "main"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-diff:
    outputs:
      common-diff: ${{ steps.common_diff.outputs.diff }}
      pytest-common-diff: ${{ steps.pytest_common_diff.outputs.diff }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set target branches
        id: target_branch
        run: |
          set -xv
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            from="origin/${GITHUB_BASE_REF}"
            to="origin/${GITHUB_HEAD_REF}"
          else
            from="${{ toJSON(github.event.before) }}"
            to="${{ toJSON(github.event.after) }}"
          fi
          {
            echo "from=${from}"
            echo "to=${to}"
          } >> "$GITHUB_OUTPUT"
      - name: Get diff of libs/common directory
        id: common_diff
        run: |
          set -xv
          diff=$(git diff "${{ steps.target_branch.outputs.from }}..${{ steps.target_branch.outputs.to }}" --diff-filter="ACDMRTUXB" --name-only -- "libs/common/**" | xargs)
          echo "diff=$diff" >> "$GITHUB_OUTPUT"
      - name: Get diff of libs/pytest-common directory
        id: pytest_common_diff
        run: |
          set -xv
          diff=$(git diff "${{ steps.target_branch.outputs.from }}..${{ steps.target_branch.outputs.to }}" --diff-filter="ACDMRTUXB" --name-only -- "libs/pytest-common/**" | xargs)
          echo "diff=$diff" >> "$GITHUB_OUTPUT"
  common-test:
    needs:
      - check-diff
    if: needs.check-diff.outputs.common-diff != '' || github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./libs/common
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get full Python version
        id: full-python-version
        run: echo "version=$(python -c 'import sys; print("-".join(str(v) for v in sys.version_info))')" >> $GITHUB_OUTPUT
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "./libs/common/uv.lock"
      - name: Install dependencies
        run: uv sync --group dev
      - name: Run tests
        run: uv run poe test
      - if: ${{ matrix.python-version == '3.12' && !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: libs-common
          path: ./libs/common/coverage
  pytest-common-test:
    needs:
      - check-diff
    if: needs.check-diff.outputs.pytest-common-diff != '' || github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./libs/pytest-common
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get full Python version
        id: full-python-version
        run: echo "version=$(python -c 'import sys; print("-".join(str(v) for v in sys.version_info))')" >> $GITHUB_OUTPUT
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "./libs/pytest-common/uv.lock"
      - name: Install dependencies
        run: uv sync --group dev
      - name: Run tests
        run: uv run poe test
      - if: ${{ matrix.python-version == '3.12' && !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: libs-pytest-common
          path: ./libs/pytest-common/coverage
  report:
    needs:
      - check-diff
      - common-test
      - pytest-common-test
    if: ${{ !failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        if: needs.check-diff.outputs.common-diff != '' || github.event_name == 'push'
        with:
          name: libs-common
          path: ./libs/common/coverage
      - uses: actions/download-artifact@v4
        if: needs.check-diff.outputs.pytest-common-diff != '' || github.event_name == 'push'
        with:
          name: libs-pytest-common
          path: ./libs/pytest-common/coverage
      - uses: k1LoW/octocov-action@v1
        if: needs.check-diff.outputs.common-diff != '' || github.event_name == 'push'
        with:
          config: ./libs/common/.octocov.yml
      - uses: k1LoW/octocov-action@v1
        if: needs.check-diff.outputs.pytest-common-diff != '' || github.event_name == 'push'
        with:
          config: ./libs/pytest-common/.octocov.yml
      - name: Setup pages
        run: |
          mkdir -p coverage/html/libs
          echo "<ul>" > coverage/html/index.html
          if [ -d "libs/common/coverage/htmlcov" ]; then
            mv libs/common/coverage/htmlcov coverage/html/libs/common
            echo "<li><a href="libs/common">libs/common</li>" >> coverage/html/index.html
          fi
          if [ -d "libs/pytest-common/coverage/htmlcov"]; then
            mv libs/pytest-common/coverage/htmlcov coverage/html/libs/pytest-common
            echo "<li><a href="libs/pytest-common">libs/pytest-common</li>" >> coverage/html/index.html
          fi
          echo "</ul>" >> coverage/html/index.html
      - uses: rajyan/preview-pages@v1
        with:
          source-dir: coverage/html
          branch-per-commit: ${{ github.event_name == 'pull_request' }}
          pr-comment: hide_and_recreate
